title: BaseballCV Documentation
description: Documentation for BaseballCV - Computer Vision Tools for Baseball Analytics

# Use local theme (not remote_theme)
theme: just-the-docs

url: https://www.baseballcv.com

# Enable search
search_enabled: true

# Enable heading anchors
heading_anchors: true

# Logo
logo: "/assets/images/logo.png"

# Aux links
aux_links:
  "BaseballCV on GitHub":
    - "//github.com/BaseballCV/BaseballCV"

# Footer
footer_content: "Copyright &copy; 2024 BaseballCV. Distributed by an <a href=\"https://github.com/BaseballCV/BaseballCV/tree/main/LICENSE\">MIT license.</a>"

# Plugins
plugins:
  - jekyll-seo-tag

# Callouts
callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: red