title: BaseballCV Documentation
description: Documentation for BaseballCV - Computer Vision Tools for Baseball Analytics

# Use local theme instead of remote theme
theme: just-the-docs

# Remove this line:
# remote_theme: just-the-docs/just-the-docs@v0.7.0

url: https://www.baseballcv.com

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

# Enable search
search_enabled: true

# Enable heading anchors
heading_anchors: true

# Navigation structure
nav_sort: case_insensitive

# Aux links for the upper right navigation
aux_links:
  "BaseballCV on GitHub":
    - "//github.com/BaseballCV/BaseballCV"

# Footer
footer_content: "Copyright &copy; 2024 BaseballCV. Distributed by an <a href=\"https://github.com/BaseballCV/BaseballCV/tree/main/LICENSE\">MIT license.</a>"

# Plugin configuration
plugins:
  - jekyll-seo-tag

# Just the Docs color scheme
color_scheme: nil

callouts_level: quiet
callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: red