name: Sync Documentation to Web Repository

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout BaseballCV repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SYNC_TOKEN }}
        path: baseballcv-main
    
    - name: Checkout BaseballCVWeb repository
      uses: actions/checkout@v4
      with:
        repository: BaseballCV/BaseballCVWeb
        token: ${{ secrets.SYNC_TOKEN }}
        path: baseballcv-web
    
    - name: Sync documentation files
      run: |
        echo "Syncing docs to BaseballCVWeb..."
        
        cd baseballcv-web
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'README.md' -exec rm -rf {} +
        
        cp -r ../baseballcv-main/docs/* .
        
        echo "Files synced successfully"
    
    - name: Commit and push changes
      run: |
        cd baseballcv-web
        
        git config user.name "Documentation Sync Bot"
        git config user.email "noreply@baseballcv.com"
        
        if git diff --quiet && git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git add .
        
        COMMIT_MSG="Sync docs from BaseballCV@${GITHUB_SHA:0:7} - $(date -u)"
        git commit -m "$COMMIT_MSG"
        
        git push origin main
        
        echo "Documentation synced successfully"
