name: Sync Documentation to Web Repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout BaseballCV repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SYNC_TOKEN }}
        fetch-depth: 2
        path: baseballcv-main
    
    - name: Check if docs changed
      id: docs_check
      run: |
        cd baseballcv-main
        if git diff --name-only HEAD^ HEAD | grep -q "^docs/"; then
          echo "docs_changed=true" >> $GITHUB_OUTPUT
          echo "Documentation changes detected"
        else
          echo "docs_changed=false" >> $GITHUB_OUTPUT
          echo "No documentation changes detected"
        fi
    
    - name: Checkout BaseballCVWeb repository
      if: steps.docs_check.outputs.docs_changed == 'true'
      uses: actions/checkout@v4
      with:
        repository: BaseballCV/BaseballCVWeb
        token: ${{ secrets.SYNC_TOKEN }}
        path: baseballcv-web
    
    - name: Sync documentation files
      if: steps.docs_check.outputs.docs_changed == 'true'
      run: |
        echo "Syncing docs to BaseballCVWeb..."
        
        cd baseballcv-web
        find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'README.md' -exec rm -rf {} +
        
        cp -r ../baseballcv-main/docs/* .
        
        echo "Files synced successfully"
    
    - name: Commit and push changes
      if: steps.docs_check.outputs.docs_changed == 'true'
      run: |
        cd baseballcv-web
        
        git config user.name "Documentation Sync Bot"
        git config user.email "noreply@baseballcv.com"
        
        if git diff --quiet && git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git add .
        
        COMMIT_MSG="Sync docs from BaseballCV@${GITHUB_SHA:0:7} - $(date -u)"
        git commit -m "$COMMIT_MSG"
        
        git push origin main
        
        echo "Documentation synced successfully"
